public class Exercise2 {

    /*String myFields = 'Name, FirstName, LastName, Phone, Mobile, OtherPhone, Email, MailingAddress';
    String firstNameWhere = 'FirstName';
    String lastNameWhere = 'LastName';
    String PhoneWhere = 'Phone, ';
        
    public static List<Contacts> retriveContacts (String LastName, String FirstName, String Phone, Integer maxNrRecords ){
        
        String myQueryString = 'SELECT' + myFields + ' FROM Contact WHERE ';
        
        if (LastName && FirstName != null) 
            myQueryString += firstNameWhere + ' = ' + FirstName + ' AND ' + lastNameWhere + ' = ' + LastName;
        else{ 
            myQueryString += PhoneWhere + ' = ' + Phone;
        }   
        
        return List <Contacts> = Database.query(myQueryString);
                
    }*/ 
    
    
}