public class MP3_Player {
    
    /*Public String Song
    {
        get{
            if( Song == null){
                return 'No song was selected';
            }
            else Song;
        };
        private set{};
        
    }
    
    public void Play(String Song){
        
        return Song;
        
    }
    
    public void Stop(String Song){
        
    	return isSongPlayed = false;    
    }*/
    
}